In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../data/cleaned_phishing.csv")

In [5]:
df.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [55]:
url_features = [
'URLLength',
'DomainLength',
'IsDomainIP',
'TLDLength',
'NoOfSubDomain',
'HasObfuscation',
'NoOfObfuscatedChar',
'NoOfLettersInURL',
'NoOfDegitsInURL',
'NoOfEqualsInURL',
'NoOfQMarkInURL',
'NoOfAmpersandInURL',
'NoOfOtherSpecialCharsInURL',
'IsHTTPS',
'Bank',
'Pay',
'Crypto'
]

X = df[url_features]
y = df['label']

In [56]:
df.shape

(235795, 52)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 52 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   URLLength                   235795 non-null  int64
 1   DomainLength                235795 non-null  int64
 2   IsDomainIP                  235795 non-null  int64
 3   TLD                         235795 non-null  object
 4   URLSimilarityIndex          235795 non-null  float64
 5   CharContinuationRate        235795 non-null  float64
 6   TLDLegitimateProb           235795 non-null  float64
 7   URLCharProb                 235795 non-null  float64
 8   TLDLength                   235795 non-null  int64
 9   NoOfSubDomain               235795 non-null  int64
 10  HasObfuscation              235795 non-null  int64
 11  NoOfObfuscatedChar          235795 non-null  int64
 12  ObfuscationRatio            235795 non-null  float64
 13  NoOfLettersInURL            235795 non-null  int64
 14  LetterRatioInURL            235795 non-null  float64
 15  NoOfDegitsInURL             235795 non-null  int64
 16  DegitRatioInURL             235795 non-null  float64
 17  NoOfEqualsInURL             235795 non-null  int64
 18  NoOfQMarkInURL              235795 non-null  int64
 19  NoOfAmpersandInURL          235795 non-null  int64
 20  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 21  SpacialCharRatioInURL       235795 non-null  float64
 22  IsHTTPS                     235795 non-null  int64
 23  LineOfCode                  235795 non-null  int64
 24  LargestLineLength           235795 non-null  int64
 25  HasTitle                    235795 non-null  int64
 26  DomainTitleMatchScore       235795 non-null  float64
 27  URLTitleMatchScore          235795 non-null  float64
 28  HasFavicon                  235795 non-null  int64
 29  Robots                      235795 non-null  int64
 30  IsResponsive                235795 non-null  int64
 31  NoOfURLRedirect             235795 non-null  int64
 32  NoOfSelfRedirect            235795 non-null  int64
 33  HasDescription              235795 non-null  int64
 34  NoOfPopup                   235795 non-null  int64
 35  NoOfiFrame                  235795 non-null  int64
 36  HasExternalFormSubmit       235795 non-null  int64
 37  HasSocialNet                235795 non-null  int64
 38  HasSubmitButton             235795 non-null  int64
 39  HasHiddenFields             235795 non-null  int64
 40  HasPasswordField            235795 non-null  int64
 41  Bank                        235795 non-null  int64
 42  Pay                         235795 non-null  int64
 43  Crypto                      235795 non-null  int64
 44  HasCopyrightInfo            235795 non-null  int64
 45  NoOfImage                   235795 non-null  int64
 46  NoOfCSS                     235795 non-null  int64
 47  NoOfJS                      235795 non-null  int64
 48  NoOfSelfRef                 235795 non-null  int64
 49  NoOfEmptyRef                235795 non-null  int64
 50  NoOfExternalRef             235795 non-null  int64
 51  label                       235795 non-null  int64
dtypes: float64(10), int64(41), object(1)
memory usage: 93.5+ MB

In [58]:
df.isnull().sum()

URLLength                     0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
label                         0
dtype: int64

In [59]:
from sklearn.model_selection import train_test_split

In [10]:
import matplotlib.pyplot as plt

In [11]:
X = df.drop("label", axis=1)
y = df["label"]

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [14]:
lr = LogisticRegression(max_iter=1000)
rf = RandomForestClassifier(random_state=42)
gb = GradientBoostingClassifier(random_state=42)

In [60]:
print(X_train.dtypes)
print(y_train.unique())

URLLength                       int64
DomainLength                    int64
IsDomainIP                      int64
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
TLDLength                       int64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
ObfuscationRatio              float64
NoOfLettersInURL                int64
LetterRatioInURL              float64
NoOfDegitsInURL                 int64
DegitRatioInURL               float64
NoOfEqualsInURL                 int64
NoOfQMarkInURL                  int64
NoOfAmpersandInURL              int64
NoOfOtherSpecialCharsInURL      int64
SpacialCharRatioInURL         float64
IsHTTPS                         int64
LineOfCode                      int64
LargestLineLength               int64
HasTitle                        int64
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
NoOfSelfRedirect                int64
HasDescription                  int64
NoOfPopup                       int64
NoOfiFrame                      int64
HasExternalFormSubmit           int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfSelfRef                     int64
NoOfEmptyRef                    int64
NoOfExternalRef                 int64
dtype: object
[1 0]

In [16]:
# Drop non-numeric columns
df = df.drop(columns=["FILENAME", "URL", "Domain", "Title"], errors="ignore")

In [17]:
X = df.drop("label", axis=1)
y = df["label"]

In [18]:
print(df["label"].unique())
print(df["label"].value_counts())

[1 0]
label
1    134850
0    100945
Name: count, dtype: int64

In [62]:
print("X shape:", X.shape)
print("y shape:", y.shape)
print("Unique labels:", y.unique())
print("Label counts:\n", y.value_counts())
print("Any null in y:", y.isnull().sum())

X shape: (235795, 17)
y shape: (235795,)
Unique labels: [1 0]
Label counts:
 label
1    134850
0    100945
Name: count, dtype: int64
Any null in y: 0

In [63]:
# Features and Target
X = df.drop("label", axis=1)
y = df["label"]

# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [64]:
X_train.dtypes

URLLength                       int64
DomainLength                    int64
IsDomainIP                      int64
TLD                            object
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
TLDLength                       int64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
ObfuscationRatio              float64
NoOfLettersInURL                int64
LetterRatioInURL              float64
NoOfDegitsInURL                 int64
DegitRatioInURL               float64
NoOfEqualsInURL                 int64
NoOfQMarkInURL                  int64
NoOfAmpersandInURL              int64
NoOfOtherSpecialCharsInURL      int64
SpacialCharRatioInURL         float64
IsHTTPS                         int64
LineOfCode                      int64
LargestLineLength               int64
HasTitle                        int64
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
NoOfSelfRedirect                int64
HasDescription                  int64
NoOfPopup                       int64
NoOfiFrame                      int64
HasExternalFormSubmit           int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfSelfRef                     int64
NoOfEmptyRef                    int64
NoOfExternalRef                 int64
dtype: object

In [22]:
X = X.replace({True: 1, False: 0})

In [23]:
X = X.select_dtypes(exclude=["object"])

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [25]:
X_train.dtypes

URLLength                       int64
DomainLength                    int64
IsDomainIP                      int64
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
TLDLength                       int64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
ObfuscationRatio              float64
NoOfLettersInURL                int64
LetterRatioInURL              float64
NoOfDegitsInURL                 int64
DegitRatioInURL               float64
NoOfEqualsInURL                 int64
NoOfQMarkInURL                  int64
NoOfAmpersandInURL              int64
NoOfOtherSpecialCharsInURL      int64
SpacialCharRatioInURL         float64
IsHTTPS                         int64
LineOfCode                      int64
LargestLineLength               int64
HasTitle                        int64
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
NoOfSelfRedirect                int64
HasDescription                  int64
NoOfPopup                       int64
NoOfiFrame                      int64
HasExternalFormSubmit           int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfSelfRef                     int64
NoOfEmptyRef                    int64
NoOfExternalRef                 int64
dtype: object

In [26]:
lr.fit(X_train, y_train)
rf.fit(X_train, y_train)
gb.fit(X_train, y_train)

c:\Users\anjal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GradientBoostingClassifier(random_state=42)

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report,confusion_matrix

In [28]:
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    return {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred)
    }

In [29]:
results = pd.DataFrame({
    "Logistic Regression": evaluate_model(lr, X_test, y_test),
    "Random Forest": evaluate_model(rf, X_test, y_test),
    "Gradient Boosting": evaluate_model(gb, X_test, y_test)
}).T

results

                     Accuracy  Precision    Recall  F1 Score
Logistic Regression  0.999852   0.999926  0.999815   0.99987
Random Forest        1.000000   1.000000  1.000000   1.00000
Gradient Boosting    1.000000   1.000000  1.000000   1.00000

In [30]:
X = df.drop("label", axis=1)
y = df["label"]

print("Unique labels:", y.unique())
print("Nulls in y:", y.isnull().sum())

Unique labels: [1 0]
Nulls in y: 0

In [31]:
X = df.drop("label", axis=1)
print(X.columns)

Index(['URLLength', 'DomainLength', 'IsDomainIP', 'TLD', 'URLSimilarityIndex',
       'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength',
       'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar',
       'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL',
       'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL',
       'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength',
       'HasTitle', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon',
       'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect',
       'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit',
       'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields',
       'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo',
       'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef',
       'NoOfExternalRef'],
      dtype='object')

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [65]:
print(X.dtypes)

URLLength                       int64
DomainLength                    int64
IsDomainIP                      int64
TLD                            object
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
TLDLength                       int64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
ObfuscationRatio              float64
NoOfLettersInURL                int64
LetterRatioInURL              float64
NoOfDegitsInURL                 int64
DegitRatioInURL               float64
NoOfEqualsInURL                 int64
NoOfQMarkInURL                  int64
NoOfAmpersandInURL              int64
NoOfOtherSpecialCharsInURL      int64
SpacialCharRatioInURL         float64
IsHTTPS                         int64
LineOfCode                      int64
LargestLineLength               int64
HasTitle                        int64
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
NoOfSelfRedirect                int64
HasDescription                  int64
NoOfPopup                       int64
NoOfiFrame                      int64
HasExternalFormSubmit           int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfSelfRef                     int64
NoOfEmptyRef                    int64
NoOfExternalRef                 int64
dtype: object

In [34]:
X = df.select_dtypes(include=['int64', 'float64'])
X = X.drop("label", axis=1)

y = df["label"]

In [35]:
print(X.select_dtypes(include='object').columns)

Index([], dtype='object')

In [36]:
print("X shape:", X.shape)
print("Nulls in X:", X.isnull().sum().sum())
print("Nulls in y:", y.isnull().sum())

X shape: (235795, 50)
Nulls in X: 0
Nulls in y: 0

In [37]:
import numpy as np

# Define X and y properly
y = df["label"]
X = df.drop(columns=["label"])

# Keep only numeric columns in X
X = X.select_dtypes(include=["int64", "float64"])

# Replace inf values if any
X = X.replace([np.inf, -np.inf], 0)

print("Final X shape:", X.shape)
print("Final y shape:", y.shape)
print("y unique:", y.unique())

Final X shape: (235795, 50)
Final y shape: (235795,)
y unique: [1 0]

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(y_train.value_counts())

label
1    107880
0     80756
Name: count, dtype: int64

In [39]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10],
    "min_samples_split": [2, 5]
}

rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(
    rf,
    param_grid,
    cv=3,              # reduce to 3 first (safer)
    scoring="f1",
    n_jobs=-1,
    error_score="raise"   # VERY IMPORTANT
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best F1 Score:", grid.best_score_)

Best Parameters: {'max_depth': 10, 'min_samples_split': 5, 'n_estimators': 200}
Best F1 Score: 1.0

In [40]:
best_model = grid.best_estimator_
grid.best_params_

{'max_depth': 10, 'min_samples_split': 5, 'n_estimators': 200}

In [41]:
evaluate_model(best_model, X_test, y_test)
print(classification_report(y_test, best_model.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     20189
           1       1.00      1.00      1.00     26970

    accuracy                           1.00     47159
   macro avg       1.00      1.00      1.00     47159
weighted avg       1.00      1.00      1.00     47159

In [42]:
import pandas as pd

feature_importance = pd.Series(
    best_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feature_importance.head(10))

URLSimilarityIndex    0.201571
NoOfExternalRef       0.166691
LineOfCode            0.132153
NoOfImage             0.110106
NoOfSelfRef           0.085245
NoOfJS                0.079281
HasSocialNet          0.033608
NoOfCSS               0.029553
HasDescription        0.023273
HasCopyrightInfo      0.022938
dtype: float64

In [43]:
best_model.predict_proba(X_test)

array([[9.83885556e-05, 9.99901611e-01],
       [4.61763522e-04, 9.99538236e-01],
       [1.93201236e-04, 9.99806799e-01],
       ...,
       [8.03399563e-05, 9.99919660e-01],
       [2.62172411e-04, 9.99737828e-01],
       [1.09427990e-03, 9.98905720e-01]])

In [44]:
X.shape

(235795, 50)

In [45]:
X = df.drop("label", axis=1)

In [46]:
feature_columns = X.columns.tolist()

import joblib

joblib.dump({
    "model": best_model,
    "features": feature_columns
}, "model/phishing_model.pkl")

['model/phishing_model.pkl']

In [69]:
print(X.columns)

Index(['URLLength', 'DomainLength', 'IsDomainIP', 'URLSimilarityIndex',
       'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength',
       'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar',
       'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL',
       'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL',
       'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL',
       'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength',
       'HasTitle', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon',
       'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect',
       'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit',
       'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields',
       'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo',
       'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef',
       'NoOfExternalRef'],
      dtype='object')

In [48]:
import joblib

joblib.dump({
    "model": best_model,
    "features": X.columns.tolist()
}, "model/phishing_model.pkl")

['model/phishing_model.pkl']

In [49]:
print(X.columns.tolist())

['URLLength', 'DomainLength', 'IsDomainIP', 'TLD', 'URLSimilarityIndex', 'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength', 'HasTitle', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef', 'NoOfExternalRef']

In [50]:
import joblib

joblib.dump({
    "model": best_model,
    "features": X.columns.tolist()
}, "model/phishing_model.pkl")

['model/phishing_model.pkl']

In [51]:
print(X.columns.tolist())

['URLLength', 'DomainLength', 'IsDomainIP', 'TLD', 'URLSimilarityIndex', 'CharContinuationRate', 'TLDLegitimateProb', 'URLCharProb', 'TLDLength', 'NoOfSubDomain', 'HasObfuscation', 'NoOfObfuscatedChar', 'ObfuscationRatio', 'NoOfLettersInURL', 'LetterRatioInURL', 'NoOfDegitsInURL', 'DegitRatioInURL', 'NoOfEqualsInURL', 'NoOfQMarkInURL', 'NoOfAmpersandInURL', 'NoOfOtherSpecialCharsInURL', 'SpacialCharRatioInURL', 'IsHTTPS', 'LineOfCode', 'LargestLineLength', 'HasTitle', 'DomainTitleMatchScore', 'URLTitleMatchScore', 'HasFavicon', 'Robots', 'IsResponsive', 'NoOfURLRedirect', 'NoOfSelfRedirect', 'HasDescription', 'NoOfPopup', 'NoOfiFrame', 'HasExternalFormSubmit', 'HasSocialNet', 'HasSubmitButton', 'HasHiddenFields', 'HasPasswordField', 'Bank', 'Pay', 'Crypto', 'HasCopyrightInfo', 'NoOfImage', 'NoOfCSS', 'NoOfJS', 'NoOfSelfRef', 'NoOfEmptyRef', 'NoOfExternalRef']

In [66]:
import joblib

# IMPORTANT: use only numeric columns
X = df.drop(columns=["label"])
X = X.select_dtypes(include=["int64", "float64"])

feature_columns = X.columns.tolist()

print("Final training features count:", len(feature_columns))

joblib.dump({
    "model": best_model,
    "features": feature_columns
}, "../model/phishing_model.pkl")

print("Model saved successfully")

Final training features count: 50
Model saved successfully

In [68]:
print("Train Accuracy:", best_model.score(X_train, y_train))
print("Test Accuracy:", best_model.score(X_test, y_test))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- TLD

In [67]:
print(y.value_counts())

label
1    134850
0    100945
Name: count, dtype: int64

In [70]:
joblib.dump({
    "model": best_model,
    "features": url_features
}, "model/phishing_model.pkl")

['model/phishing_model.pkl']

In [5]:
# Use only URL-based features that Flask extracts

feature_columns = [
'URLLength',
'DomainLength',
'IsDomainIP',
'TLDLength',
'NoOfSubDomain',
'HasObfuscation',
'NoOfObfuscatedChar',
'NoOfLettersInURL',
'NoOfDegitsInURL',
'NoOfEqualsInURL',
'NoOfQMarkInURL',
'NoOfAmpersandInURL',
'NoOfOtherSpecialCharsInURL',
'IsHTTPS',
'Bank',
'Pay',
'Crypto'
]

X = df[feature_columns]
y = df['label']

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=25,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

print("Train accuracy:", model.score(X_train, y_train))
print("Test accuracy:", model.score(X_test, y_test))

Train accuracy: 0.9984308403486079
Test accuracy: 0.9970737292987553

In [ ]:
import joblib

joblib.dump({
    "model": model,
    "features": feature_columns
}, "../model/phishing_model.pkl")

print("Model saved successfully")

Model saved successfully

: